Removed both flanges from forward region of beampipe
eic/ip6 pull request #16
Opened 2022-08-24 03:50 UTC by rymilton

2022-08-24 22:29 UTC, wdconinc commented on ip6/central_beampipe.xml
>            <zplane z="1790.01 * mm" OD=" 92.06 * mm"/>
We don't need a duplicate plane at 1750/1790 anymore.
```suggestion
          <zplane z="1750.00 * mm" OD=" 92.06 * mm"/>
```

2022-08-24 22:30 UTC, wdconinc requested changes
We should also get rid of the definitiions of `BeampipeDownstreamFlange1Thickness` and `BeampipeDownstreamFlange2Thickness` up on the top of the file.

2022-08-24 22:55 UTC, rymilton commented on ip6/central_beampipe.xml
>            <zplane z="1790.01 * mm" OD=" 92.06 * mm"/>
Do we need the ` <zplane z="1750.00 * mm" OD=" 92.06 * mm"/>`?

2022-08-24 23:03 UTC, wdconinc commented on ip6/central_beampipe.xml
>            <zplane z="1790.01 * mm" OD=" 92.06 * mm"/>
Probably not... but I don't have the overlap checks with the epic repo working yet, so I didn't want to suggest that we remove it. It *should* work fine without. So if you can do that and test with a full (geant4) overlap check, we can go that route.

2022-08-24 23:49 UTC, rymilton commented on ip6/central_beampipe.xml
>            <zplane z="1790.01 * mm" OD=" 92.06 * mm"/>
Ah, yeah there's overlap after removing that line. Here's the overlap:
```
-------- WWWW ------- G4Exception-START -------- WWWW -------
*** G4Exception : GeomVol1002
      issued by : G4PVPlacement::CheckOverlaps()
Overlap with volume already placed !
          Overlap is detected for volume DRICH_11:11 (G4UnionSolid)
          with AV_849!BeamPipe_assembly_20#20!v_downstream_matter_11#11:32 (G4SubtractionSolid) volume's
          local point (-106.182,-48.9111,2511.32), overlapping by at least: 1.57605 mm 
NOTE: Reached maximum fixed number -1- of overlaps reports for this volume !
*** This is just a warning message. ***
-------- WWWW -------- G4Exception-END --------- WWWW -------
```

2022-08-24 23:49 UTC, rymilton commented on ip6/central_beampipe.xml
>            <zplane z="1790.01 * mm" OD=" 92.06 * mm"/>
I'll keep that line then. Running an overlap check currently but seems fine so far.

2022-08-25 00:14 UTC, rymilton commented on ip6/central_beampipe.xml
>            <zplane z="1790.01 * mm" OD=" 92.06 * mm"/>
Confirmed no overlaps with the line present.

2022-08-25 00:31 UTC, wdconinc approved these changes

2022-08-25 00:32 UTC, merged