Draft: 24 implement b0 pbwo4 ecal
eic/ip6 pull request #25
Opened 2022-09-29 23:10 UTC by rahmans1

### Briefly, what does this PR introduce?
Implement a PbWO4 calorimeter that can be used in the B0 region instead of the preshower.

### What kind of change does this PR introduce?
- [X ] New feature (issue #24 )

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators
- [X] This is a draft PR. DO NOT MERGE.  

### Does this PR introduce breaking changes? What changes might users need to make to their code?
User needs to modify [farforward.xml](https://github.com/eic/ip6/blob/24-implement-b0-pbwo4-ecal/ip6/far_forward.xml#L7) and replace B0_preshower.xml with B0_ECal.xml to run sims with the ECal

### Does this PR change default behavior?
We can decide later if we want to keep the preshower or the ECal as the default in the main geometry

2022-10-02 19:31 UTC, wdconinc requested changes

2022-10-02 19:31 UTC, wdconinc commented on ip6.xml
> +    <constant name="B0ECal_ID" value="166"/>
This conflicts with what was introduced in #26. All changes to ID structures are best added as separate PRs. @shimasnd @rahmans1

2022-10-02 19:31 UTC, wdconinc commented on ip6/far_forward.xml
> +  <include ref="far_forward/B0_ECal.xml"/>
Commented out code should be avoided.

Why comment it out?
- If it currently not working but will need to be used in the future:
  - file an issue with info on what is needed,
  - add the issue as a reference along with the commented out block.
- If is not going to be needed:
  - remove the code,
  - move the referred to `B0_preshower.xml` file into `unused/` in its directory.

2022-10-02 19:31 UTC, wdconinc commented on src/B0ECal_geo.cpp
> +typedef ROOT::Math::XYPoint Point;
Modernize: use `using`

2022-10-02 19:31 UTC, wdconinc commented on src/B0ECal_geo.cpp
> +using namespace dd4hep;
Error prone: avoid `using namespace std` and list only the entities you actually use frequently enough for this to make a difference in readability, e.g. `using std::vector`.

2022-10-02 19:31 UTC, wdconinc commented on src/B0ECal_geo.cpp
> +                                     int id);
Preparation for merge geometry: Add these two geometry helpers to a separate utility header as in epic.

2022-10-02 19:35 UTC, ajentsch commented
How else should we toggle between the preshower and the EMCAL? We need both
geometries until a final decision is made by the project.

On Sun, Oct 2, 2022, 3:31 PM Wouter Deconinck ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In ip6.xml <https://github.com/eic/ip6/pull/25#discussion_r985284009>:
>
> > @@ -43,6 +43,7 @@
>      <constant name="ZDCEcal_ID"              value="163"/>
>      <constant name="ZDCHcal_ID"              value="164"/>
>      <constant name="VacuumMagnetElement_1_ID"        value="165"/>
> +    <constant name="B0ECal_ID" value="166"/>
>
> This conflicts with what was introduced in #26
> <https://github.com/eic/ip6/pull/26>. All changes to ID structures are
> best added as separate PRs. @shimasnd <https://github.com/shimasnd>
> @rahmans1 <https://github.com/rahmans1>
> ------------------------------
>
> In ip6/far_forward.xml
> <https://github.com/eic/ip6/pull/25#discussion_r985284369>:
>
> > +  <!--
> +         <include ref="far_forward/B0_preshower.xml"/>
> +  -->
> +  <include ref="far_forward/B0_ECal.xml"/>
>
> Commented out code should be avoided.
>
> Why comment it out?
>
>    - If it currently not working but will need to be used in the future:
>       - file an issue with info on what is needed,
>       - add the issue as a reference along with the commented out block.
>    - If is not going to be needed:
>       - remove the code,
>       - move the referred to B0_preshower.xml file into unused/ in its
>       directory.
>
> ------------------------------
>
> In src/B0ECal_geo.cpp
> <https://github.com/eic/ip6/pull/25#discussion_r985284690>:
>
> > +#include "DDRec/DetectorData.h"
> +#include "DDRec/Surface.h"
> +#include <XML/Helper.h>
> +
> +//////////////////////////////////////////////////
> +// Far Forward B0 Electromagnetic Calorimeter
> +//////////////////////////////////////////////////
> +
> +using namespace std;
> +using namespace dd4hep;
> +
> +static std::tuple<int, int> add_individuals(Detector& desc, Assembly& env, xml::Collection_t& plm,
> +                                            SensitiveDetector& sens, int id);
> +static std::tuple<int, int> add_disk(Detector& desc, Assembly& env, xml::Collection_t& plm, SensitiveDetector& sens,
> +                                     int id);
> +typedef ROOT::Math::XYPoint Point;
>
> Modernize: use using
> ------------------------------
>
> In src/B0ECal_geo.cpp
> <https://github.com/eic/ip6/pull/25#discussion_r985284946>:
>
> > +using namespace std;
> +using namespace dd4hep;
>
> Error prone: avoid using namespace std and list only the entities you
> actually use frequently enough for this to make a difference in
> readability, e.g. using std::vector.
> ------------------------------
>
> In src/B0ECal_geo.cpp
> <https://github.com/eic/ip6/pull/25#discussion_r985285106>:
>
> > +static std::tuple<int, int> add_individuals(Detector& desc, Assembly& env, xml::Collection_t& plm,
> +                                            SensitiveDetector& sens, int id);
> +static std::tuple<int, int> add_disk(Detector& desc, Assembly& env, xml::Collection_t& plm, SensitiveDetector& sens,
> +                                     int id);
>
> Preparation for merge geometry: Add these two geometry helpers to a
> separate utility header as in epic.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/eic/ip6/pull/25#pullrequestreview-1127683653>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADABSFYJW4NSYHZ42KU4ZDDWBHPIBANCNFSM6AAAAAAQZHM3WQ>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2022-10-02 19:55 UTC, wdconinc commented
> How else should we toggle between the preshower and the EMCAL? We need both geometries until a final decision is made by the project.

Not disagreeing with the goal here, but this implementation leads to dead code in comment blocks. This is not the only area where we are making a decision between two detector types, but in other places we are not having to comment/uncomment includes.

2022-10-02 19:56 UTC, ajentsch commented
Ahh okay, I see. What is the better way you'd prefer us to do it?

On Sun, Oct 2, 2022, 3:55 PM Wouter Deconinck ***@***.***>
wrote:

> How else should we toggle between the preshower and the EMCAL? We need
> both geometries until a final decision is made by the project.
>
> Not disagreeing with the goal here, but this implementation leads to dead
> code in comment blocks. This is not the only area where we are making a
> decision between two detector types, but in other places we are not having
> to comment/uncomment includes.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/eic/ip6/pull/25#issuecomment-1264720421>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADABSF7XJ2GRC4RQF77YUNLWBHSERANCNFSM6AAAAAAQZHM3WQ>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2022-10-02 20:14 UTC, rahmans1 commented on ip6.xml
> +    <constant name="B0ECal_ID" value="166"/>
For now, should I revert this commit? That should take away the conflict.  And introduce a separate PR for ID change?

2022-10-02 20:15 UTC, wdconinc commented
Is one of the two major configurations for this production with preshower and one without? if so, I'd suggest using a `far_forward_arches.xml` and a `far_forward_brycecanyon.xml` for now.

2022-10-02 20:19 UTC, ajentsch commented
Originally no, we weren't. But since Sakib got it done, I think we will. I
can make the configurations for the two options tomorrow morning - I also
need to figure out how to do things with the magnet settings. We will have
a bit of a challenge since some MC samples will literally be useless with
one magnet setting, and vice versa (meaning 18x275 GeV DVCS cannot be used
with 41 GeV magnet settings).

On Sun, Oct 2, 2022, 4:16 PM Wouter Deconinck ***@***.***>
wrote:

> Is one of the two major configurations for this production with preshower
> and one without? if so, I'd suggest using a far_forward_arches.xml and a
> far_forward_brycecanyon.xml for now.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/eic/ip6/pull/25#issuecomment-1264724289>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADABSFYE66NQNNBK4YFLBW3WBHUQHANCNFSM6AAAAAAQZHM3WQ>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2022-10-02 20:19 UTC, wdconinc commented on ip6.xml
> +    <constant name="B0ECal_ID" value="166"/>
You can just modify it to an ID that's not used yet even after the other changes.

2022-10-02 20:20 UTC, rahmans1 commented on ip6/far_forward.xml
> +  <include ref="far_forward/B0_ECal.xml"/>
> Is one of the two major configurations for this production with preshower and one without? if so, I'd suggest using a `far_forward_arches.xml` and a `far_forward_brycecanyon.xml` for now.

Are you suggesting making two copies of far_forward.xml. And including the preshower in one and the emcal in the other? Doesn't epic by default look for the far_forward.xml?

2022-10-02 20:21 UTC, wdconinc commented on ip6/far_forward.xml
> +  <include ref="far_forward/B0_ECal.xml"/>
Yes, but epic_brycecanyon could look for far_forward_brycecanyon etc

2022-10-02 20:30 UTC, rahmans1 commented on ip6/far_forward.xml
> +  <include ref="far_forward/B0_ECal.xml"/>
ok. understood. So, then there would need to be a separate PR to add epic_brycecanyon on the epic repo?

2022-10-02 20:34 UTC, wdconinc commented on ip6/far_forward.xml
> +  <include ref="far_forward/B0_ECal.xml"/>
Yes. First prep here, probably add as matrix to tests for overlap, then file as PR to epic.

2022-10-05 03:11 UTC, rahmans1 commented on src/B0ECal_geo.cpp
> +                                     int id);
Addressed by commit [57beb70](https://github.com/eic/ip6/pull/25/commits/57beb70dfec047f4d9491a1ae5f5908ed396e313), [4ccd587](https://github.com/eic/ip6/pull/25/commits/4ccd587ac78224d02aad1589446550577f99d132),  and [2a6d510](https://github.com/eic/ip6/pull/25/commits/2a6d510d2a9ce78cf8bda1dbb76207a8abff0b17). Please check if it's reasonable now.

2022-10-05 13:13 UTC, rahmans1 commented on ip6/far_forward.xml
> +  <include ref="far_forward/B0_ECal.xml"/>
ok. i created the versioned far forward files [6f583d0](https://github.com/eic/ip6/pull/25/commits/6f583d07dd060d16778d90c349fff91f486abb71). Is there any thing else that needs to change within ip6 like the ip6.xml? I didn't understand what you meant by adding as matrix to tests for overlap.

2022-10-05 13:15 UTC, rahmans1 commented on src/B0ECal_geo.cpp
> +typedef ROOT::Math::XYPoint Point;
Addressed

2022-10-11 02:13 UTC, wdconinc approved these changes
This looks good.

Any idea why the required overlap checks are not reporting back?

2022-10-11 02:16 UTC, wdconinc commented
> Any idea why the required overlap checks are not reporting back?

Ah, right, turning it into a matrix job changes the name so it doesn't match the requirements anymore. This should be all good then.

2022-10-11 02:20 UTC, wdconinc commented
Updated branch with changes in master.

2022-10-11 17:43 UTC, merged